### ISSUE TITLE
Collapse / Expand Selected Folder doesn't seem to work

### ISSUE THREAD

**Issue by nickchomey** [nathonius/obsidian-collapse-all#32]
When I right click on folders, I dont see any option for expand/collapse. 

![image](https://user-images.githubusercontent.com/88559987/174645720-984aa893-48a3-4e06-84ba-c0b44ae973b8.png)

**Comment by OfficerHalf** [comment]
There's a setting for it in the plugin's settings. Make sure that's on. Otherwise, perhaps another plugin is conflicting? It seems to be working for me.

**Comment by OfficerHalf** [comment]
Interesting. This plugin doesn't touch CodeMirror, but it could be that some other change broke it.

I'm not on insiders, so I won't be able to check.

**Comment by OfficerHalf** [comment]
Cool, not sure what went wrong. Let me know if you see the same behavior again.
